// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	accountdom "github.com/ricky7171/te-marketplace/internal/modules/account/domain"

	mock "github.com/stretchr/testify/mock"
)

// AccountRepository is an autogenerated mock type for the AccountRepository type
type AccountRepository struct {
	mock.Mock
}

// GetByFields provides a mock function with given fields: fields
func (_m *AccountRepository) GetByFields(fields map[string]string) (*accountdom.Account, error) {
	ret := _m.Called(fields)

	var r0 *accountdom.Account
	if rf, ok := ret.Get(0).(func(map[string]string) *accountdom.Account); ok {
		r0 = rf(fields)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*accountdom.Account)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(map[string]string) error); ok {
		r1 = rf(fields)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAccountRepository interface {
	mock.TestingT
	Cleanup(func())
}

// NewAccountRepository creates a new instance of AccountRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAccountRepository(t mockConstructorTestingTNewAccountRepository) *AccountRepository {
	mock := &AccountRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
