// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/ricky7171/te-marketplace/internal/modules/account/application/service"
	"github.com/ricky7171/te-marketplace/internal/modules/account/presentation"
	"github.com/ricky7171/te-marketplace/internal/router"
)

// Injectors from injector.go:

func InitializedRouter() *router.Router {
	engine := gin.Default()
	authenticationServiceImpl := accountappservice.NewAuthenticationServiceImpl()
	handler := accountpresent.NewHandler(authenticationServiceImpl)
	routerRouter := router.NewRouter(engine, handler)
	return routerRouter
}

// injector.go:

var accAppServAuthnSet = wire.NewSet(accountappservice.NewAuthenticationServiceImpl, wire.Bind(new(accountappservice.AuthenticationService), new(*accountappservice.AuthenticationServiceImpl)))

var accPresentHandlerSet = wire.NewSet(accAppServAuthnSet, accountpresent.NewHandler)

var routerSet = wire.NewSet(gin.Default, accPresentHandlerSet, router.NewRouter)
