// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/gin-gonic/gin"
	"github.com/google/wire"
	"github.com/ricky7171/te-marketplace/internal/helper"
	"github.com/ricky7171/te-marketplace/internal/library_wrapper"
	"github.com/ricky7171/te-marketplace/internal/modules/account/application/service"
	"github.com/ricky7171/te-marketplace/internal/modules/account/domain/repository"
	"github.com/ricky7171/te-marketplace/internal/modules/account/infrastructure/repository"
	"github.com/ricky7171/te-marketplace/internal/modules/account/presentation"
	"github.com/ricky7171/te-marketplace/internal/router"
)

// Injectors from injector.go:

func InitializedRouter() *router.Router {
	engine := gin.Default()
	accountRepositoryPg := accountinfrarepository.NewAccountRepositoryPg()
	myJwtImpl := library_wrapper.NewMyJwtImpl()
	helperJwtImpl := helper.NewHelperJwtImpl(myJwtImpl)
	authenticationServiceImpl := accountappservice.NewAuthenticationServiceImpl(accountRepositoryPg, helperJwtImpl)
	handler := accountpresent.NewHandler(authenticationServiceImpl)
	routerRouter := router.NewRouter(engine, handler)
	return routerRouter
}

// injector.go:

var accDomRepoSet = wire.NewSet(accountinfrarepository.NewAccountRepositoryPg, wire.Bind(new(accountdomrepository.AccountRepository), new(*accountinfrarepository.AccountRepositoryPg)))

var myJwtSet = wire.NewSet(library_wrapper.NewMyJwtImpl, wire.Bind(new(library_wrapper.MyJwt), new(*library_wrapper.MyJwtImpl)))

var helperJwtSet = wire.NewSet(myJwtSet, helper.NewHelperJwtImpl, wire.Bind(new(helper.HelperJwt), new(*helper.HelperJwtImpl)))

var accAppServAuthnSet = wire.NewSet(accDomRepoSet, helperJwtSet, accountappservice.NewAuthenticationServiceImpl, wire.Bind(new(accountappservice.AuthenticationService), new(*accountappservice.AuthenticationServiceImpl)))

var accPresentHandlerSet = wire.NewSet(accAppServAuthnSet, accountpresent.NewHandler)

var routerSet = wire.NewSet(gin.Default, accPresentHandlerSet, router.NewRouter)
