// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MyGinContext is an autogenerated mock type for the MyGinContext type
type MyGinContext struct {
	mock.Mock
}

// JSON provides a mock function with given fields: code, obj
func (_m *MyGinContext) JSON(code int, obj interface{}) {
	_m.Called(code, obj)
}

// ShouldBindJSON provides a mock function with given fields: obj
func (_m *MyGinContext) ShouldBindJSON(obj interface{}) error {
	ret := _m.Called(obj)

	var r0 error
	if rf, ok := ret.Get(0).(func(interface{}) error); ok {
		r0 = rf(obj)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewMyGinContext interface {
	mock.TestingT
	Cleanup(func())
}

// NewMyGinContext creates a new instance of MyGinContext. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMyGinContext(t mockConstructorTestingTNewMyGinContext) *MyGinContext {
	mock := &MyGinContext{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
