// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import (
	accountdom "github.com/ricky7171/te-marketplace/internal/modules/account/domain"
	mock "github.com/stretchr/testify/mock"
)

// AuthenticationService is an autogenerated mock type for the AuthenticationService type
type AuthenticationService struct {
	mock.Mock
}

// Login provides a mock function with given fields: credential
func (_m *AuthenticationService) Login(credential accountdom.Credential) (interface{}, error) {
	ret := _m.Called(credential)

	var r0 interface{}
	if rf, ok := ret.Get(0).(func(accountdom.Credential) interface{}); ok {
		r0 = rf(credential)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(accountdom.Credential) error); ok {
		r1 = rf(credential)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewAuthenticationService interface {
	mock.TestingT
	Cleanup(func())
}

// NewAuthenticationService creates a new instance of AuthenticationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAuthenticationService(t mockConstructorTestingTNewAuthenticationService) *AuthenticationService {
	mock := &AuthenticationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
